#!/bin/zsh

student_number=201111365
student_name=坂口和彦
alias mail_command="ssh `coins-imac` 'sendmail -t'"

attachment(){
<<EOT
------
Content-Type: $1; charset=$2
Content-Disposition: attachment; filename="$3"
Content-Transfer-Encoding: base64

EOT
base64
}

{
<<EOT
To: stec@score.cs.tsukuba.ac.jp
Subject: STEC:report
Content-Type: multipart/mixed; boundary="----"

EOT
(echo $student_number ; echo $student_name) | attachment text/plain UTF-8 student.txt
for f in $@ ; attachment text/x-scheme UTF-8 "stec-`head -n 1 $f | tail -c +2`.rkt" < $f
echo --------
} | mail_command
